package alpacadecimal_test

import (
	"math"
	"math/big"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/alpacahq/alpacadecimal"
)

// All hardcoded expected strings in this file were generated by running the
// same operations against github.com/shopspring/decimal v1.4.0 and match its
// output exactly. Where the exact shopspring result carries more than 19
// fractional digits, the expected value is shopspring's result after
// Truncate(19): this package truncates such results to 19 fractional digits
// (the package-wide precision limit), which is the documented divergence.

func TestTrigMatchesShopspring(t *testing.T) {
	cases := []struct {
		input, atan, sin, cos, tan string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"0.5", "0.4636476090008061", "0.4794255386042030028", "0.8775825618903727162", "0.5463024898437905"},
		{"-0.5", "-0.4636476090008061", "-0.4794255386042030028", "0.8775825618903727162", "-0.5463024898437905"},
		{"1", "0.7853981633974483306", "0.8414709848078965448", "0.5403023058681396587", "1.5574077246549025"},
		{"2", "1.1071487177940904984", "0.9092974268256816662", "-0.4161468365471424519", "-2.1850398632615185"},
		{"-2", "-1.1071487177940904984", "-0.9092974268256816662", "-0.4161468365471424519", "2.1850398632615185"},
		{"3.141592653589793", "1.2626272556789116041", "0.0000000000000000978", "-0.9999999999999999999", "-0.0000000000000000978"},
		{"0.785398163397448", "0.665773750028353735", "0.7071067811865473113", "0.707106781186547744", "0.999999999999999381"},
		{"5", "1.3734007669450158012", "-0.958924274663138409", "0.2836621854632264662", "-3.3805150062465829"},
		{"-12.345", "-1.4899683534864189361", "0.2195669967379325725", "0.9755974241168765545", "0.2250590164654108878"},
		{"100.5", "1.5608464064020913975", "-0.0309599667832668469", "0.9995206253283515977", "-0.0309748153251927309"},
	}
	for _, c := range cases {
		t.Run(c.input, func(t *testing.T) {
			d := alpacadecimal.RequireFromString(c.input)
			require.Equal(t, c.atan, d.Atan().String(), "Atan")
			require.Equal(t, c.sin, d.Sin().String(), "Sin")
			require.Equal(t, c.cos, d.Cos().String(), "Cos")
			require.Equal(t, c.tan, d.Tan().String(), "Tan")
		})
	}

	t.Run("zero", func(t *testing.T) {
		// matches shopspring v1.4.0: Atan/Sin/Tan return the input, Cos is 1
		zero := alpacadecimal.RequireFromString("0")
		require.Equal(t, "0", zero.Atan().String())
		require.Equal(t, "0", zero.Sin().String())
		require.Equal(t, "1", zero.Cos().String())
		require.Equal(t, "0", zero.Tan().String())
	})

	t.Run("huge argument", func(t *testing.T) {
		// matches shopspring v1.4.0 (Truncate(19)) except the final digit:
		// the exact result needs 40 significant digits and the zerodecimal
		// fallback's 128-bit coefficient holds at most 39, so the last
		// fractional digit truncates (shopspring/udecimal: ...246099).
		d := alpacadecimal.RequireFromString("100000000000000000000")
		require.Equal(t, "1.5707963267948965612", d.Atan().String())
		require.Equal(t, "101416272413079734262.291175030637624609", d.Tan().String())
	})
}

func TestTrigDivisionPrecisionSensitivity(t *testing.T) {
	// Atan and Tan divide at the DivisionPrecision package var (Sin/Cos are
	// division-free); changing it must change the output exactly the way it
	// does in shopspring v1.4.0.
	alpacadecimal.DivisionPrecision = 8
	defer func() { alpacadecimal.DivisionPrecision = 16 }()

	cases := []struct {
		input, atan, tan string
	}{
		// matches shopspring v1.4.0 with DivisionPrecision = 8 (Truncate(19))
		{"2", "1.1071487101158278306", "-2.18503986"},
		{"5", "1.3734007700000000612", "-3.38051501"},
		{"-12.345", "-1.4899683519868682612", "0.2250590162696160396"},
	}
	for _, c := range cases {
		d := alpacadecimal.RequireFromString(c.input)
		require.Equal(t, c.atan, d.Atan().String(), "Atan(%s)", c.input)
		require.Equal(t, c.tan, d.Tan().String(), "Tan(%s)", c.input)
	}
}

func TestLnMatchesShopspring(t *testing.T) {
	cases := []struct {
		input     string
		precision int32
		expected  string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"13.3", 2, "2.59"},
		{"579.161", 10, "6.3615805046"},
		{"2", 19, "0.6931471805599453094"},
		{"0.9", 8, "-0.10536052"},
		{"0.75", 19, "-0.2876820724517809274"},
		{"123456789.987654321", 30, "18.631401774168018074"},
		{"2.718281828459045", 16, "0.9999999999999999"},
		{"0.00001", -5, "0"},
	}
	for _, c := range cases {
		d := alpacadecimal.RequireFromString(c.input)
		r, err := d.Ln(c.precision)
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "Ln(%s, %d)", c.input, c.precision)
	}

	t.Run("errors", func(t *testing.T) {
		// matches shopspring v1.4.0 error messages
		_, err := alpacadecimal.RequireFromString("0").Ln(5)
		require.EqualError(t, err, "cannot represent natural logarithm of 0, result: -infinity")
		_, err = alpacadecimal.RequireFromString("-1").Ln(5)
		require.EqualError(t, err, "cannot calculate natural logarithm for negative decimals")
	})
}

func TestExpTaylorMatchesShopspring(t *testing.T) {
	cases := []struct {
		input     string
		precision int32
		expected  string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"26.1", 2, "216314672147.06"},
		{"26.1", 20, "216314672147.0576728406292867408"},
		{"26.1", -10, "220000000000"},
		{"0", 2, "1"},
		{"-5.5", 8, "0.00408677"},
		{"1", 19, "2.7182818284590452354"},
		{"2.5", 30, "12.182493960703473438"},
		{"-0.00001", -5, "0"},
	}
	for _, c := range cases {
		d := alpacadecimal.RequireFromString(c.input)
		r, err := d.ExpTaylor(c.precision)
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "ExpTaylor(%s, %d)", c.input, c.precision)
	}
}

func TestExpHullAbrhamMatchesShopspring(t *testing.T) {
	require.Equal(t, 1000, alpacadecimal.ExpMaxIterations)

	cases := []struct {
		input     string
		precision uint32
		expected  string
	}{
		// matches shopspring v1.4.0
		{"26.1", 2, "220000000000"},
		{"26.1", 20, "216314672147.05767284"},
		{"0", 5, "1"},
		{"-5.5", 8, "0.00408677"},
		{"1", 19, "2.718281828459045235"},
		{"50", 1, "5180000000000000000000"},
		// shopspring quirk (ported faithfully): an argument below the
		// small-value threshold returns 10^exponent, not 1
		{"0.000123", 2, "0.000001"},
		{"0.0001", 2, "0.0001"},
	}
	for _, c := range cases {
		d := alpacadecimal.RequireFromString(c.input)
		r, err := d.ExpHullAbrham(c.precision)
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "ExpHullAbrham(%s, %d)", c.input, c.precision)
	}

	t.Run("errors", func(t *testing.T) {
		// matches shopspring v1.4.0 error messages
		_, err := alpacadecimal.RequireFromString("1000000").ExpHullAbrham(8)
		require.EqualError(t, err, "over/underflow threshold, exp(x) cannot be calculated precisely")

		alpacadecimal.ExpMaxIterations = 1
		defer func() { alpacadecimal.ExpMaxIterations = 1000 }()
		_, err = alpacadecimal.RequireFromString("26.1").ExpHullAbrham(8)
		require.EqualError(t, err, "exact value cannot be calculated in <=ExpMaxIterations iterations")
	})
}

func TestPowWithPrecisionMatchesShopspring(t *testing.T) {
	cases := []struct {
		base, exp string
		precision int32
		expected  string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"4", "4", 2, "256"},
		{"5", "5.73", 5, "10118.080371595015625"},
		{"-3", "-6", 10, "0.0013717421"},
		{"0.5", "-2.5", 16, "5.6568542494923801952"},
		{"2", "-2.5", 30, "0.1767766952966368811"},
		{"13.3", "0.001", 16, "1.0025911151866182617"},
		{"2", "10", 5, "1024"},
		{"2", "0", 5, "1"},
		{"0", "2", 5, "0"},
	}
	for _, c := range cases {
		b := alpacadecimal.RequireFromString(c.base)
		e := alpacadecimal.RequireFromString(c.exp)
		r, err := b.PowWithPrecision(e, c.precision)
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "PowWithPrecision(%s, %s, %d)", c.base, c.exp, c.precision)
	}

	t.Run("errors", func(t *testing.T) {
		// matches shopspring v1.4.0 error messages
		zero := alpacadecimal.RequireFromString("0")
		_, err := zero.PowWithPrecision(zero, 5)
		require.EqualError(t, err, "cannot represent undefined value of 0**0")
		_, err = zero.PowWithPrecision(alpacadecimal.NewFromInt(-1), 5)
		require.EqualError(t, err, "cannot represent infinity value of 0 ** y, where y < 0")
		_, err = alpacadecimal.NewFromInt(-2).PowWithPrecision(alpacadecimal.RequireFromString("1.5"), 5)
		require.EqualError(t, err, "cannot represent imaginary value of x ** y, where x < 0 and y is non-integer decimal")
	})
}

func TestPowInt32MatchesShopspring(t *testing.T) {
	cases := []struct {
		base     string
		exp      int32
		expected string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"4", 4, "256"},
		{"3.13", 5, "300.4150512793"},
		{"629.25", 5, "98654323103449.5673828125"},
		{"0.5", -4, "16"},
		{"-1.5", 3, "-3.375"},
		{"2", -10, "0.0009765625"},
		{"7", 0, "1"},
		// shopspring's exact result 0.0000000004656612873077392578125 has 31
		// fractional digits; this package truncates at 19
		{"0.5", 31, "0.0000000004656612873"},
		// shopspring quirk (ported faithfully): abs(MinInt32) overflows, so
		// the exponent loop never runs and 1 is returned
		{"2", math.MinInt32, "1"},
	}
	for _, c := range cases {
		b := alpacadecimal.RequireFromString(c.base)
		r, err := b.PowInt32(c.exp)
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "PowInt32(%s, %d)", c.base, c.exp)
	}

	t.Run("errors", func(t *testing.T) {
		// matches shopspring v1.4.0 error message
		_, err := alpacadecimal.RequireFromString("0").PowInt32(0)
		require.EqualError(t, err, "cannot represent undefined value of 0**0")
	})

	t.Run("zero to negative power panics", func(t *testing.T) {
		// shopspring v1.4.0 panics identically (1/0**|exp| division by zero)
		require.PanicsWithValue(t, "decimal division by 0", func() {
			_, _ = alpacadecimal.RequireFromString("0").PowInt32(-2)
		})
	})
}

func TestPowBigIntMatchesShopspring(t *testing.T) {
	cases := []struct {
		base     string
		exp      int64
		expected string
	}{
		// matches shopspring v1.4.0 (Truncate(19))
		{"3", 3, "27"},
		{"629.25", 5, "98654323103449.5673828125"},
		{"2", -100, "0"},
		{"-1.5", 7, "-17.0859375"},
		{"3.13", 10, "90249.2030351444485666084"},
		{"-3", -6, "0.0013717421124829"},
		{"7", 0, "1"},
	}
	for _, c := range cases {
		b := alpacadecimal.RequireFromString(c.base)
		r, err := b.PowBigInt(big.NewInt(c.exp))
		require.NoError(t, err)
		require.Equal(t, c.expected, r.String(), "PowBigInt(%s, %d)", c.base, c.exp)
	}

	t.Run("errors", func(t *testing.T) {
		// matches shopspring v1.4.0 error message
		_, err := alpacadecimal.RequireFromString("0").PowBigInt(big.NewInt(0))
		require.EqualError(t, err, "cannot represent undefined value of 0**0")
	})

	t.Run("zero to negative power panics", func(t *testing.T) {
		// shopspring v1.4.0 panics identically (1/0**|exp| division by zero)
		require.PanicsWithValue(t, "decimal division by 0", func() {
			_, _ = alpacadecimal.RequireFromString("0").PowBigInt(big.NewInt(-1))
		})
	})
}

func TestRescalePair(t *testing.T) {
	t.Run("two fixed values are returned unchanged", func(t *testing.T) {
		d1 := alpacadecimal.RequireFromString("1.5")
		d2 := alpacadecimal.RequireFromString("2.25")
		r1, r2 := alpacadecimal.RescalePair(d1, d2)
		require.True(t, r1.Equal(d1))
		require.True(t, r2.Equal(d2))
		require.Equal(t, int32(-12), r1.Exponent())
		require.Equal(t, int32(-12), r2.Exponent())
	})

	t.Run("fixed and high-precision fallback", func(t *testing.T) {
		d1 := alpacadecimal.RequireFromString("1.5")
		d2 := alpacadecimal.RequireFromString("0.1234567890123456789")
		require.Equal(t, int32(-19), d2.Exponent())
		r1, r2 := alpacadecimal.RescalePair(d1, d2)
		require.True(t, r1.Equal(d1))
		require.True(t, r2.Equal(d2))
		require.Equal(t, int32(-19), r1.Exponent())
		require.Equal(t, int32(-19), r2.Exponent())
	})

	t.Run("big integer and fixed", func(t *testing.T) {
		d1 := alpacadecimal.RequireFromString("100000000000000000000")
		require.Equal(t, int32(0), d1.Exponent())
		d2 := alpacadecimal.RequireFromString("1.5")
		r1, r2 := alpacadecimal.RescalePair(d1, d2)
		require.True(t, r1.Equal(d1))
		require.True(t, r2.Equal(d2))
		require.Equal(t, int32(-12), r1.Exponent())
		require.Equal(t, int32(-12), r2.Exponent())
	})

	t.Run("coefficient beyond 128 bits", func(t *testing.T) {
		// DOMAIN DIVERGENCE (zerodecimal fallback): 10^50 exceeds the 128-bit
		// coefficient domain, so parsing it errors instead of succeeding (the
		// udecimal fallback stored it exactly via big.Int coefficients).
		_, err := alpacadecimal.NewFromString("100000000000000000000000000000000000000000000000000")
		require.Error(t, err)
		require.Contains(t, err.Error(), "exceeds the 128-bit decimal domain")
	})

	t.Run("two fallbacks of different precision", func(t *testing.T) {
		d1 := alpacadecimal.RequireFromString("0.12345678901234")
		d2 := alpacadecimal.RequireFromString("0.1234567890123456789")
		r1, r2 := alpacadecimal.RescalePair(d1, d2)
		require.True(t, r1.Equal(d1))
		require.True(t, r2.Equal(d2))
		require.Equal(t, int32(-19), r1.Exponent())
		require.Equal(t, int32(-19), r2.Exponent())
	})

	t.Run("zero is returned unchanged", func(t *testing.T) {
		// a zero coefficient cannot carry an arbitrary exponent in this
		// package's representation (documented RescalePair limitation)
		d1 := alpacadecimal.RequireFromString("0")
		d2 := alpacadecimal.RequireFromString("0.1234567890123456789")
		r1, r2 := alpacadecimal.RescalePair(d1, d2)
		require.True(t, r1.Equal(d1))
		require.True(t, r2.Equal(d2))
	})
}
