package alpacadecimal_test

import (
	"bytes"
	"encoding/binary"
	"encoding/gob"
	"encoding/json"
	"math"
	"math/big"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/alpacahq/alpacadecimal"
)

// All hardcoded expected strings in this file were generated by running the
// same operations against github.com/shopspring/decimal v1.4.0 and match its
// output exactly, except where a comment documents a deliberate divergence
// (the package-wide truncation convention beyond 19 fractional digits).

func TestParityScientificNotation(t *testing.T) {
	t.Run("valid forms", func(t *testing.T) {
		cases := []struct {
			input    string
			expected string
		}{
			{"1e5", "100000"},
			{"1E5", "100000"},
			{"1.23e-4", "0.000123"},
			{"-1.5e3", "-1500"},
			{"0.5e2", "50"},
			{"1.e5", "100000"},
			{"2E+5", "200000"},
			{"1e19", "10000000000000000000"},
		}
		for _, c := range cases {
			t.Run(c.input, func(t *testing.T) {
				d, err := alpacadecimal.NewFromString(c.input)
				require.NoError(t, err)
				require.Equal(t, c.expected, d.String())
				require.True(t, d.Equal(alpacadecimal.RequireFromString(c.expected)))

				require.NotPanics(t, func() {
					r := alpacadecimal.RequireFromString(c.input)
					require.Equal(t, c.expected, r.String())
				})
			})
		}
	})

	t.Run("invalid forms", func(t *testing.T) {
		for _, input := range []string{"1e", "1e5.5", "e5", "1ee5"} {
			t.Run(input, func(t *testing.T) {
				_, err := alpacadecimal.NewFromString(input)
				require.Error(t, err)
				require.Panics(t, func() { alpacadecimal.RequireFromString(input) })
			})
		}
	})

	t.Run("UnmarshalJSON unquoted", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, json.Unmarshal([]byte(`1.5e3`), &d))
		require.Equal(t, "1500", d.String())
	})

	t.Run("UnmarshalJSON quoted", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, json.Unmarshal([]byte(`"1.5e3"`), &d))
		require.Equal(t, "1500", d.String())
	})

	t.Run("UnmarshalText", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, d.UnmarshalText([]byte("1.5e3")))
		require.Equal(t, "1500", d.String())
	})
}

func TestParityNewExponentRange(t *testing.T) {
	t.Run("large positive exponents", func(t *testing.T) {
		require.NotPanics(t, func() {
			require.Equal(t, "50000000000000000000", alpacadecimal.New(5, 19).String())
		})
		require.NotPanics(t, func() {
			s := alpacadecimal.New(1, 300).String()
			require.Len(t, s, 301) // "1" followed by 300 zeros
			require.Equal(t, "1"+strings.Repeat("0", 300), s)
		})
		require.Equal(t, "0", alpacadecimal.New(0, 19).String())
	})

	t.Run("large negative exponents", func(t *testing.T) {
		require.Equal(t, "0.0000000000000000001", alpacadecimal.New(1, -19).String())

		// Truncation convention: digits beyond 19 fractional places are
		// truncated, so New(1, -20) is 0. shopspring v1.4.0 keeps arbitrary
		// precision and returns "0.00000000000000000001" here.
		require.Equal(t, "0", alpacadecimal.New(1, -20).String())
	})

	t.Run("plain", func(t *testing.T) {
		require.Equal(t, "123.456", alpacadecimal.New(123456, -3).String())
	})
}

func TestParityNewFromBigInt(t *testing.T) {
	coef := new(big.Int).Exp(big.NewInt(10), big.NewInt(250), nil) // 10^250

	t.Run("10^250 exp 0", func(t *testing.T) {
		d := alpacadecimal.NewFromBigInt(coef, 0)
		require.Equal(t, coef.String(), d.String())
		require.Len(t, d.String(), 251)
	})

	t.Run("negative 10^250 exp 199", func(t *testing.T) {
		d := alpacadecimal.NewFromBigInt(new(big.Int).Neg(coef), 199)
		expected := new(big.Int).Mul(
			new(big.Int).Neg(coef),
			new(big.Int).Exp(big.NewInt(10), big.NewInt(199), nil),
		)
		require.Equal(t, expected.String(), d.String())
		require.Len(t, d.String(), 451) // sign + 450 digits
	})

	t.Run("10^250 exp 300", func(t *testing.T) {
		d := alpacadecimal.NewFromBigInt(coef, 300)
		expected := new(big.Int).Mul(
			coef,
			new(big.Int).Exp(big.NewInt(10), big.NewInt(300), nil),
		)
		require.Equal(t, expected.String(), d.String())
		require.Len(t, d.String(), 551)
	})

	t.Run("small stays optimized", func(t *testing.T) {
		d := alpacadecimal.NewFromBigInt(big.NewInt(123), -2)
		require.Equal(t, "1.23", d.String())
		require.True(t, d.IsOptimized())
	})
}

func TestParityNewFromFloat(t *testing.T) {
	t.Run("huge floats no panic", func(t *testing.T) {
		for _, f := range []float64{1e300, math.MaxFloat64} {
			require.NotPanics(t, func() {
				d := alpacadecimal.NewFromFloat(f)
				require.Equal(t, strconv.FormatFloat(f, 'f', -1, 64), d.String())
			})
		}
	})

	t.Run("NaN and Inf panic", func(t *testing.T) {
		require.Panics(t, func() { alpacadecimal.NewFromFloat(math.NaN()) })
		require.Panics(t, func() { alpacadecimal.NewFromFloat(math.Inf(1)) })
		require.Panics(t, func() { alpacadecimal.NewFromFloat(math.Inf(-1)) })
	})

	t.Run("fast path identity", func(t *testing.T) {
		// expected strings are shopspring v1.4.0 outputs, equal to
		// strconv.FormatFloat(f, 'f', -1, 64).
		cases := []struct {
			input    float64
			expected string
		}{
			{1.23, "1.23"},
			{0.1, "0.1"},
			{2.675, "2.675"},
			{8191.999999999999, "8191.999999999999"},
			{0.000000000001, "0.000000000001"},
			{-55.55, "-55.55"},
		}
		for _, c := range cases {
			t.Run(c.expected, func(t *testing.T) {
				require.Equal(t, c.expected, alpacadecimal.NewFromFloat(c.input).String())
			})
		}
	})
}

func TestParityNewFromFloatWithExponent(t *testing.T) {
	// Rounds half away from zero; expected strings match shopspring v1.4.0.
	cases := []struct {
		input    float64
		exp      int32
		expected string
	}{
		{123.456, -2, "123.46"},
		{123.454, -2, "123.45"},
		{-123.456, -2, "-123.46"},
		{12345.0, 2, "12300"},
	}
	for _, c := range cases {
		t.Run(c.expected, func(t *testing.T) {
			require.Equal(t, c.expected, alpacadecimal.NewFromFloatWithExponent(c.input, c.exp).String())
		})
	}
}

func TestParityNewFromUint64(t *testing.T) {
	t.Run("small", func(t *testing.T) {
		d := alpacadecimal.NewFromUint64(123)
		require.Equal(t, "123", d.String())
		require.True(t, d.IsOptimized())
	})

	t.Run("max uint64", func(t *testing.T) {
		require.Equal(t, "18446744073709551615", alpacadecimal.NewFromUint64(math.MaxUint64).String())
	})
}

func TestParityNewFromBigRat(t *testing.T) {
	// expected strings match shopspring v1.4.0.
	cases := []struct {
		num, denom int64
		precision  int32
		expected   string
	}{
		{4, 5, 1, "0.8"},
		{1000, 3, 3, "333.333"},
		{2, 7, 4, "0.2857"},
		{0, 1, 0, "0"},
	}
	for _, c := range cases {
		t.Run(c.expected, func(t *testing.T) {
			d := alpacadecimal.NewFromBigRat(big.NewRat(c.num, c.denom), c.precision)
			require.Equal(t, c.expected, d.String())
		})
	}
}

func TestParityStrictParsing(t *testing.T) {
	t.Run("rejects", func(t *testing.T) {
		for _, input := range []string{".", "..", "-.", "+.", "", "-", "+", "\"1.5\"", "5..5", "--5"} {
			t.Run(input, func(t *testing.T) {
				_, err := alpacadecimal.NewFromString(input)
				require.Error(t, err, "input %q should be rejected", input)
			})
		}
	})

	t.Run("accepts", func(t *testing.T) {
		cases := []struct {
			input    string
			expected string
		}{
			{".5", "0.5"},
			{"5.", "5"},
			{"-.5", "-0.5"},
			{"9223372.", "9223372"},
			{".1234567890123", "0.1234567890123"},
		}
		for _, c := range cases {
			t.Run(c.input, func(t *testing.T) {
				d, err := alpacadecimal.NewFromString(c.input)
				require.NoError(t, err)
				require.Equal(t, c.expected, d.String())
			})
		}
	})

	t.Run("250-digit integer", func(t *testing.T) {
		digits := strings.Repeat("1234567890", 25)
		expected, ok := new(big.Int).SetString(digits, 10)
		require.True(t, ok)

		d, err := alpacadecimal.NewFromString(digits)
		require.NoError(t, err)
		require.Equal(t, expected.String(), d.String())
	})
}

func TestParityPow(t *testing.T) {
	// expected strings match shopspring v1.4.0 with default
	// PowPrecisionNegativeExponent (16).
	cases := []struct {
		base, exp string
		expected  string
	}{
		{"0", "0", "0"},  // 0^0 is undefined => 0
		{"0", "-2", "0"}, // 0^negative is infinity => 0
		{"0", "5", "0"},  // 0^positive
		{"2", "10", "1024"},
		{"2", "-2", "0.25"},
		{"-2", "3", "-8"},
		{"-2", "-3", "-0.125"},
		{"-2", "1.5", "0"}, // negative base, fractional exponent: imaginary => 0
		{"4", "0.5", "2"},
		{"5", "5.73", "10118.08037125"},
		{"1.7", "-3", "0.2035416242621616"}, // 1/4.913 rounded at 16 places
	}
	for _, c := range cases {
		t.Run(c.base+"^"+c.exp, func(t *testing.T) {
			base := alpacadecimal.RequireFromString(c.base)
			exp := alpacadecimal.RequireFromString(c.exp)
			require.Equal(t, c.expected, base.Pow(exp).String())
		})
	}
}

func TestParityDivRound(t *testing.T) {
	t.Run("negative precision", func(t *testing.T) {
		// matches shopspring v1.4.0: 100/7 = 14.28..., rounded to tens => 10
		d := alpacadecimal.NewFromInt(100).DivRound(alpacadecimal.NewFromInt(7), -1)
		require.Equal(t, "10", d.String())
	})

	t.Run("precision 19", func(t *testing.T) {
		d := alpacadecimal.NewFromInt(2).DivRound(alpacadecimal.NewFromInt(3), 19)
		require.Equal(t, "0.6666666666666666667", d.String())
	})

	t.Run("division by zero panics", func(t *testing.T) {
		one := alpacadecimal.NewFromInt(1)
		require.PanicsWithValue(t, "decimal division by 0", func() {
			one.Div(alpacadecimal.Zero)
		})
		require.PanicsWithValue(t, "decimal division by 0", func() {
			one.DivRound(alpacadecimal.Zero, 2)
		})
	})
}

func TestParityQuoRem(t *testing.T) {
	// expectedQ / expectedR match shopspring v1.4.0 exactly.
	cases := []struct {
		d, d2     string
		precision int32
		expectedQ string
		expectedR string
	}{
		{"10", "3", 1, "3.3", "0.1"},
		{"-10", "3", 1, "-3.3", "-0.1"},
		{"10", "-3", 1, "-3.3", "0.1"},
		{"-10", "-3", 1, "3.3", "-0.1"},
		{"123.456", "-7.89", 3, "-15.647", "0.00117"},
		{"1", "7", 7, "0.1428571", "0.0000003"},
		{"100", "7", -2, "0", "100"},
		{"-100", "7", -2, "0", "-100"},
		// previously broken: high-precision dividend with small divisor
		{"123.4567890123456789", "0.0001", 0, "1234567", "0.0000890123456789"},
	}
	for _, c := range cases {
		t.Run(c.d+"/"+c.d2, func(t *testing.T) {
			d := alpacadecimal.RequireFromString(c.d)
			d2 := alpacadecimal.RequireFromString(c.d2)

			q, r := d.QuoRem(d2, c.precision)
			require.Equal(t, c.expectedQ, q.String())
			require.Equal(t, c.expectedR, r.String())

			// shopspring invariant: d == d2*q + r
			require.True(t, d.Equal(d2.Mul(q).Add(r)),
				"invariant d == d2*q + r violated: %s != %s * %s + %s",
				d.String(), d2.String(), q.String(), r.String())
		})
	}
}

func TestParityShift(t *testing.T) {
	d := alpacadecimal.RequireFromString("1.5")

	t.Run("shift 19", func(t *testing.T) {
		require.NotPanics(t, func() {
			require.Equal(t, "15000000000000000000", d.Shift(19).String())
		})
	})

	t.Run("shift 25", func(t *testing.T) {
		require.NotPanics(t, func() {
			require.Equal(t, "15000000000000000000000000", d.Shift(25).String())
		})
	})

	t.Run("shift -25", func(t *testing.T) {
		// Truncation convention: 1.5 * 10^-25 needs 26 fractional digits, which
		// exceeds the 19-digit limit, so the value truncates to 0. shopspring
		// v1.4.0 keeps arbitrary precision and returns
		// "0.00000000000000000000000015" here.
		require.NotPanics(t, func() {
			require.Equal(t, "0", d.Shift(-25).String())
		})
	})
}

func TestParityRoundingExtremes(t *testing.T) {
	// Every expected string below matches shopspring v1.4.0 output for the same
	// value/places/function combination. Note Truncate with negative precision
	// is a no-op in shopspring (and here).
	cases := []struct {
		value      string
		places     int32
		round      string
		roundBank  string
		roundDown  string
		roundUp    string
		roundCeil  string
		roundFloor string
		truncate   string
	}{
		{"123", -1, "120", "120", "120", "130", "130", "120", "123"},
		{"123", -7, "0", "0", "0", "10000000", "10000000", "0", "123"},
		{"123", -19, "0", "0", "0", "10000000000000000000", "10000000000000000000", "0", "123"},
		{"123", -25, "0", "0", "0", "10000000000000000000000000", "10000000000000000000000000", "0", "123"},
		{"123", 256, "123", "123", "123", "123", "123", "123", "123"},
		{"123", 300, "123", "123", "123", "123", "123", "123", "123"},
		{"-123", -1, "-120", "-120", "-120", "-130", "-120", "-130", "-123"},
		{"-123", -7, "0", "0", "0", "-10000000", "0", "-10000000", "-123"},
		{"-123", -19, "0", "0", "0", "-10000000000000000000", "0", "-10000000000000000000", "-123"},
		{"-123", -25, "0", "0", "0", "-10000000000000000000000000", "0", "-10000000000000000000000000", "-123"},
		{"-123", 256, "-123", "-123", "-123", "-123", "-123", "-123", "-123"},
		{"-123", 300, "-123", "-123", "-123", "-123", "-123", "-123", "-123"},
		{"545", -1, "550", "540", "540", "550", "550", "540", "545"},
		{"545", -7, "0", "0", "0", "10000000", "10000000", "0", "545"},
		{"545", -19, "0", "0", "0", "10000000000000000000", "10000000000000000000", "0", "545"},
		{"545", -25, "0", "0", "0", "10000000000000000000000000", "10000000000000000000000000", "0", "545"},
		{"545", 256, "545", "545", "545", "545", "545", "545", "545"},
		{"545", 300, "545", "545", "545", "545", "545", "545", "545"},
		{"9223372", -1, "9223370", "9223370", "9223370", "9223380", "9223380", "9223370", "9223372"},
		{"9223372", -7, "10000000", "10000000", "0", "10000000", "10000000", "0", "9223372"},
		{"9223372", -19, "0", "0", "0", "10000000000000000000", "10000000000000000000", "0", "9223372"},
		{"9223372", -25, "0", "0", "0", "10000000000000000000000000", "10000000000000000000000000", "0", "9223372"},
		{"9223372", 256, "9223372", "9223372", "9223372", "9223372", "9223372", "9223372", "9223372"},
		{"9223372", 300, "9223372", "9223372", "9223372", "9223372", "9223372", "9223372", "9223372"},
		{"5.5", -1, "10", "10", "0", "10", "10", "0", "5.5"},
		{"5.5", -7, "0", "0", "0", "10000000", "10000000", "0", "5.5"},
		{"5.5", -19, "0", "0", "0", "10000000000000000000", "10000000000000000000", "0", "5.5"},
		{"5.5", -25, "0", "0", "0", "10000000000000000000000000", "10000000000000000000000000", "0", "5.5"},
		{"5.5", 256, "5.5", "5.5", "5.5", "5.5", "5.5", "5.5", "5.5"},
		{"5.5", 300, "5.5", "5.5", "5.5", "5.5", "5.5", "5.5", "5.5"},
		{"-5.5", -1, "-10", "-10", "0", "-10", "0", "-10", "-5.5"},
		{"-5.5", -7, "0", "0", "0", "-10000000", "0", "-10000000", "-5.5"},
		{"-5.5", -19, "0", "0", "0", "-10000000000000000000", "0", "-10000000000000000000", "-5.5"},
		{"-5.5", -25, "0", "0", "0", "-10000000000000000000000000", "0", "-10000000000000000000000000", "-5.5"},
		{"-5.5", 256, "-5.5", "-5.5", "-5.5", "-5.5", "-5.5", "-5.5", "-5.5"},
		{"-5.5", 300, "-5.5", "-5.5", "-5.5", "-5.5", "-5.5", "-5.5", "-5.5"},
	}
	for _, c := range cases {
		t.Run(c.value+"@"+strconv.Itoa(int(c.places)), func(t *testing.T) {
			d := alpacadecimal.RequireFromString(c.value)
			require.NotPanics(t, func() {
				require.Equal(t, c.round, d.Round(c.places).String(), "Round")
				require.Equal(t, c.roundBank, d.RoundBank(c.places).String(), "RoundBank")
				require.Equal(t, c.roundDown, d.RoundDown(c.places).String(), "RoundDown")
				require.Equal(t, c.roundUp, d.RoundUp(c.places).String(), "RoundUp")
				require.Equal(t, c.roundCeil, d.RoundCeil(c.places).String(), "RoundCeil")
				require.Equal(t, c.roundFloor, d.RoundFloor(c.places).String(), "RoundFloor")
				require.Equal(t, c.truncate, d.Truncate(c.places).String(), "Truncate")
			})
		})
	}
}

func TestParityStringScaled(t *testing.T) {
	// expected strings match shopspring v1.4.0 (StringScaled truncates).
	cases := []struct {
		value    string
		exp      int32
		expected string
	}{
		{"1.5", -2, "1.5"},
		{"5.45", 0, "5"},
		{"545", 1, "540"},
		{"1.239", -2, "1.23"},
		{"-5.45", 0, "-5"},
	}
	for _, c := range cases {
		t.Run(c.value, func(t *testing.T) {
			d := alpacadecimal.RequireFromString(c.value)
			require.Equal(t, c.expected, d.StringScaled(c.exp))
		})
	}
}

func TestParityBinaryGob(t *testing.T) {
	values := []string{"123.45", "-0.001", "0", "123456789.123456789", "9223372", "1.5", "0.000000000000000001"}

	// shopspring's binary format is a 4-byte big-endian exponent followed by
	// the gob encoding of the big.Int coefficient; the helpers below
	// reproduce it with the standard library only, so the main module does
	// not need shopspring as a dependency.

	t.Run("alpacadecimal to shopspring format", func(t *testing.T) {
		for _, v := range values {
			t.Run(v, func(t *testing.T) {
				data, err := alpacadecimal.RequireFromString(v).MarshalBinary()
				require.NoError(t, err)
				require.Equal(t, v, shopspringFormatDecode(t, data))
			})
		}
	})

	t.Run("shopspring format to alpacadecimal", func(t *testing.T) {
		for _, v := range values {
			t.Run(v, func(t *testing.T) {
				data := shopspringFormatEncode(t, v)

				var ad alpacadecimal.Decimal
				require.NoError(t, ad.UnmarshalBinary(data))
				require.Equal(t, v, ad.String())
			})
		}
	})

	t.Run("gob struct round-trip", func(t *testing.T) {
		type wrapper struct {
			D  alpacadecimal.Decimal
			ND alpacadecimal.NullDecimal
		}

		for _, v := range values {
			t.Run(v, func(t *testing.T) {
				in := wrapper{
					D:  alpacadecimal.RequireFromString(v),
					ND: alpacadecimal.NewNullDecimal(alpacadecimal.RequireFromString(v).Neg()),
				}

				var buf bytes.Buffer
				require.NoError(t, gob.NewEncoder(&buf).Encode(in))

				var out wrapper
				require.NoError(t, gob.NewDecoder(&buf).Decode(&out))
				require.Equal(t, in.D.String(), out.D.String())
				require.True(t, out.ND.Valid)
				require.Equal(t, in.ND.Decimal.String(), out.ND.Decimal.String())
			})
		}
	})
}

// shopspringFormatEncode builds the exact bytes shopspring's MarshalBinary
// produces for a plain decimal string: big-endian int32 exponent, then the
// big.Int gob encoding of the coefficient.
func shopspringFormatEncode(t *testing.T, value string) []byte {
	t.Helper()
	exp := 0
	digits := value
	if dot := strings.IndexByte(value, '.'); dot >= 0 {
		exp = -(len(value) - dot - 1)
		digits = value[:dot] + value[dot+1:]
	}
	coef, ok := new(big.Int).SetString(digits, 10)
	require.True(t, ok)
	gobBytes, err := coef.GobEncode()
	require.NoError(t, err)
	out := make([]byte, 4, 4+len(gobBytes))
	binary.BigEndian.PutUint32(out, uint32(int32(exp)))
	return append(out, gobBytes...)
}

// shopspringFormatDecode decodes shopspring-format bytes (as shopspring's
// UnmarshalBinary would) and renders the value as a trimmed decimal string.
func shopspringFormatDecode(t *testing.T, data []byte) string {
	t.Helper()
	require.GreaterOrEqual(t, len(data), 4)
	exp := int32(binary.BigEndian.Uint32(data[:4]))
	coef := new(big.Int)
	require.NoError(t, coef.GobDecode(data[4:]))

	neg := coef.Sign() < 0
	abs := new(big.Int).Abs(coef).String()
	var s string
	switch {
	case exp >= 0:
		s = abs + strings.Repeat("0", int(exp))
	default:
		frac := int(-exp)
		if frac >= len(abs) {
			abs = strings.Repeat("0", frac-len(abs)+1) + abs
		}
		s = abs[:len(abs)-frac] + "." + abs[len(abs)-frac:]
		s = strings.TrimRight(s, "0")
		s = strings.TrimRight(s, ".")
	}
	if s == "" {
		s = "0"
	}
	if neg && s != "0" {
		s = "-" + s
	}
	return s
}

func TestParityJSONNullAndScan(t *testing.T) {
	t.Run("UnmarshalJSON null is a no-op", func(t *testing.T) {
		d := alpacadecimal.NewFromInt(5)
		require.NoError(t, d.UnmarshalJSON([]byte("null")))
		require.Equal(t, "5", d.String())
	})

	t.Run("Scan float32", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, d.Scan(float32(123.456)))
		require.True(t, d.Equal(alpacadecimal.NewFromFloat(float64(float32(123.456)))))
		require.Equal(t, "123.45600128173828", d.String()) // matches shopspring v1.4.0
	})

	t.Run("Scan int errors", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.Error(t, d.Scan(int(5))) // like shopspring, plain int is not supported
	})

	t.Run("Scan uint64", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, d.Scan(uint64(5)))
		require.Equal(t, "5", d.String())
	})

	t.Run("Scan quoted string", func(t *testing.T) {
		var d alpacadecimal.Decimal
		require.NoError(t, d.Scan("\"1.5\"")) // shopspring unquotes in Scan
		require.Equal(t, "1.5", d.String())
	})

	t.Run("NullDecimal Scan nil", func(t *testing.T) {
		var nd alpacadecimal.NullDecimal
		require.NoError(t, nd.Scan(nil))
		require.False(t, nd.Valid)
	})
}

func TestParityFloat64Exactness(t *testing.T) {
	cases := []struct {
		value string
		f     float64
		exact bool
	}{
		{"0.5", 0.5, true},
		{"0.1", 0.1, false},
		{"1", 1, true},
		{"0.3", 0.3, false},
	}
	for _, c := range cases {
		t.Run(c.value, func(t *testing.T) {
			f, exact := alpacadecimal.RequireFromString(c.value).Float64()
			require.Equal(t, c.f, f)
			require.Equal(t, c.exact, exact)
		})
	}

	t.Run("InexactFloat64", func(t *testing.T) {
		require.Equal(t, 0.1, alpacadecimal.RequireFromString("0.1").InexactFloat64())
	})
}

func TestParityIntPart(t *testing.T) {
	t.Run("huge fallback no panic", func(t *testing.T) {
		huge := alpacadecimal.NewFromBigInt(new(big.Int).Exp(big.NewInt(10), big.NewInt(250), nil), 0)
		require.NotPanics(t, func() { huge.IntPart() })
	})

	t.Run("just out of fixed range", func(t *testing.T) {
		d := alpacadecimal.RequireFromString("-9223372.036854775808")
		require.False(t, d.IsOptimized())
		require.Equal(t, int64(-9223372), d.IntPart())
	})
}

func TestParityRepresentationInvariance(t *testing.T) {
	t.Run("Sub shrinks back to fixed", func(t *testing.T) {
		big := alpacadecimal.RequireFromString("9223373")
		require.False(t, big.IsOptimized())

		d := big.Sub(alpacadecimal.NewFromInt(2))
		require.Equal(t, "9223371", d.String())
		require.True(t, d.IsOptimized())
	})

	t.Run("Mod of fallback fits", func(t *testing.T) {
		d := alpacadecimal.RequireFromString("9223373.5")
		require.False(t, d.IsOptimized())

		m := d.Mod(alpacadecimal.NewFromInt(2))
		require.Equal(t, "1.5", m.String())
		require.True(t, m.IsOptimized())
	})

	t.Run("Truncate of fallback fits", func(t *testing.T) {
		d := alpacadecimal.RequireFromString("9223372.9")
		require.False(t, d.IsOptimized())

		tr := d.Truncate(0)
		require.Equal(t, "9223372", tr.String())
		require.True(t, tr.IsOptimized())
	})

	t.Run("Round of fallback fits", func(t *testing.T) {
		d := alpacadecimal.RequireFromString("9223372.4")
		require.False(t, d.IsOptimized())

		r := d.Round(0)
		require.Equal(t, "9223372", r.String())
		require.True(t, r.IsOptimized())
	})
}
