name: Go

on: [push]

concurrency:
  # One active run per workflow + branch
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23', '1.24', '1.25' ]

    steps:
    - uses: actions/checkout@v6
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...
